kalabash_sievefilters/urls.py
"""Sieve urls."""

from django.urls import path

from . import views

app_name = 'kalabash_sievefilters'

urlpatterns = [
    path('', views.index, name="index"),
    path('savefs/<str:name>/', views.savefs, name="fs_save"),
    path('newfs/', views.new_filters_set, name="fs_add"),
    path('removefs/<str:name>/', views.remove_filters_set,
         name="fs_delete"),
    path('activatefs/<str:name>/', views.activate_filters_set,
         name="fs_activate"),
    path('downloadfs/<str:name>/', views.download_filters_set,
         name="fs_download"),
    path('templates/<str:ftype>/', views.get_templates,
         name="templates_get"),
    path('<str:setname>/newfilter/', views.newfilter,
         name="filter_add"),
    path('<str:setname>/editfilter/<path:fname>/', views.editfilter,
         name="filter_change"),
    path('<str:setname>/removefilter/<path:fname>/', views.removefilter,
         name="filter_delete"),
    path('<str:setname>/togglestate/<path:fname>/',
         views.toggle_filter_state, name="filter_toggle_state"),
    path('<str:setname>/moveup/<path:fname>/',
         views.move_filter_up, name="filter_move_up"),
    path('<str:setname>/movedown/<path:fname>/',
         views.move_filter_down, name="filter_move_down"),
    path('<str:name>/', views.getfs, name="fs_get"),
]

kalabash_sievefilters/templates/kalabash_sievefilters/filter.html
{% extends "common/generic_modal_form.html" %}
{% load i18n form_tags sfilters_tags %}

{% block modal_css_classes %}modal-lg{% endblock %}

{% block formbody %}
  {% if oldname %}<input type="hidden" name="oldname" value="{{ oldname }}" />{% endif %}
  {% render_field form.name %}
  <h6>{% trans "Conditions" %}</h6>
  <div id="addfilterlist">
    <div id="matchtype">
      {% render_field form.match_type %}
    </div>
    <div id="hide" style="display:{{ hidestyle }}">
      {% for ec in conds_nb %}
      {% display_condition form ec %}
      {% endfor %}
    </div>
  </div>
  <h6>{% trans "Actions" %}</h6>
  <div id="addfilterlist">
    {% for ea in actions_nb %}
    {% display_action form ea %}
    {% endfor %}
  </div>
{% endblock %}

kalabash_sievefilters/templates/kalabash_sievefilters/guieditor.html
{% load i18n sfilters_tags %}
{% if fs.filters %}
<table class="table table-striped table-bordered">
  <tr>
    <th width="10%">{% trans "Actions" %}</th>
    <th>{% trans "Name" %}</th>
    <th width="5%">{% trans "Active" %}</th>
  </tr>
  {% for filter in fs.filters %}
  <tr>
    <td>{% filter_actions fs.name filter forloop.counter forloop.last %}</td>
    <td>{{ filter.name }}</td>
    <td>
      <a name="togglestate" 
         class={% if filter.enabled %}"green"{% else %}"red"{% endif %}
         href="{% url 'kalabash_sievefilters:filter_toggle_state' fs.name filter.name %}">
        {{ filter.enabled|yesno }}
      </a>
    </td>
  </tr>
  {% endfor %}
</table>
{% else %}
<div class="alert alert-info">{% trans "No filter defined yet" %}</div>
{% endif %}

kalabash_sievefilters/templates/kalabash_sievefilters/index.html
{% extends "twocols.html" %}
{% load i18n static sfilters_tags %}

{% block pagetitle %}{% trans "Message filters" %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'kalabash_sievefilters/css/style.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'kalabash_sievefilters/js/lib.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dynamic_input.js' %}"></script>
<script type="text/javascript" src="{% static 'kalabash_sievefilters/js/jquery.dynfields.js' %}"></script>
<script type="text/javascript">
var histomanager = new History({
    deflocation: "{{ default_script }}",
    defcallback: loadfs
});
var cond_templates = null;
var action_templates = null;

function display_filter_errors(data) {
    $("ul.errors").remove();
    $.each(data.form_errors, function(id, value) {
        if (id.indexOf('cond') && id.indexOf('action')) {
            return;                     
        }
        var fullid = "id_" + (data.prefix ? data.prefix + "-" : "") + id;
        var $widget = $("#" + fullid);
        var ulid = fullid + "-error";
        var $ul = $("<ul />", {
            "class": "errors",
            "id": ulid
        }).append($("<li />", {
            html: value[0]
        }));
        $widget.after($ul);
    });
}

function filterform_cb() {
    cond_templates = fetch_templates("{% url 'kalabash_sievefilters:templates_get' 'condition' %}", cond_templates);
    action_templates = fetch_templates("{% url 'kalabash_sievefilters:templates_get' 'action' %}", action_templates);

    var $dc = $("#condition_0").dyncondition({
        templates: cond_templates
    }).data('dyncondition');
    var $da = $("#action_0").dynaction({
        templates: action_templates,
        hdelimiter: '{{ hdelimiter }}'
    }).data('dynaction');

    $("input[name=match_type]").click(function(e) {
        if ($(this).val() == "all") {
            $("div[id*=condition]").hide();
        } else {
            $("div[id*=condition]").show();
        }
    });

    $(".submit").on('click', function(e) {
        var counters = "conds=" + $dc.fields_cnt + "&actions=" + $da.fields_cnt;

        simple_ajax_form_post(e, {
            formid: 'filterform',
            reload_mode: 'history',
            extradata: counters,
            error_cb: display_filter_errors
        });
    });
}

$(document).ready(function() {
  $("#curfset").change(changefs);
});
</script>
{% endblock %}

{% block leftcol %}
<ul id="menu" class="nav nav-sidebar">
  <li class="nav-header">{% trans "Filter sets" %}</li>
  <li class="fset_container">
    <select id="curfset" class="form-control">
      {% if active_script %}
      <option value="{{ active_script }}">{{ active_script }} ({% trans "active" %})</option>
      {% endif %}
      {% for script in scripts %}
      <option value="{{ script }}">{{ script }}</option>
      {% endfor %}
    </select>
  </li>
  {# It will add a li item : #}
  {% sfilters_menu user %}
</ul>
{% endblock %}

{% block apparea %}
<div id="set_content">
  {% if not active_script and not scripts %}
  <div class="alert alert-info">{% trans "No filters set defined yet. You must create one in order to define filters." %}</div>
  {% endif %}
</div>
{% endblock %}

kalabash_sievefilters/templates/kalabash_sievefilters/rawfilter.html
<form action="{% url 'kalabash_sievefilters:fs_save' name %}" 
      method="POST" id="feditor" name="feditor">{% csrf_token %}
  <textarea id="scriptcontent" name="scriptcontent">{{ scriptcontent }}</textarea>
</form>